spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:db/data.sql
security:
  jwt:
    token:
      secret-key: test
      expire-length: 3600000
      server-info: test
